# This backend uses advisory locks where the database provides them (MySQL and PostgreSQL)
# and a lock table with fencing tokens where it does not (SQLite)
class Idempo::ActiveRecordBackend
  # The TTL for a lease taken by the TokenLock. It only comes into play if the process
  # holding the lock crashes or gets killed without releasing it - the lease is what
  # allows a subsequent request to take the lock over.
  LOCK_TTL_SECONDS = 5 * 60

  # Kept as-is for backwards compatibility: migrations generated by earlier versions of
  # Idempo call this, and they must keep creating exactly the one table they always did.
  # A fresh install gets both tables via `rails g idempo:install`.
  def self.create_table(via_migration)
    create_responses_table(via_migration)
  end

  def self.create_responses_table(via_migration)
    via_migration.create_table "idempo_responses", charset: "utf8mb4", collation: "utf8mb4_unicode_ci" do |t|
      t.string :idempotent_request_key, index: {unique: true}, null: false
      t.datetime :expire_at, index: true, null: false # Needs an index for cleanup
      t.binary :idempotent_response_payload, limit: Idempo::SAVED_RESPONSE_BODY_SIZE_LIMIT
      t.timestamps
    end
  end

  # Only databases without advisory locks (SQLite) actually use this table, but having it
  # on MySQL and PostgreSQL costs nothing - it just stays empty, and it means switching
  # databases later needs no schema change.
  def self.create_locks_table(via_migration)
    via_migration.create_table "idempo_locks", charset: "utf8mb4", collation: "utf8mb4_unicode_ci" do |t|
      t.string :idempotent_request_key, index: {unique: true}, null: false
      t.string :lock_token, null: false
      t.datetime :expire_at, index: true, null: false # Needs an index for cleanup
    end
  end

  class Store < Struct.new(:key, :model, :verify_lock_held)
    def lookup
      model.where(idempotent_request_key: key).where("expire_at > ?", Time.now).first&.idempotent_response_payload
    end

    def store(data:, ttl:)
      # MySQL does not support datetime with subsecont precision, so ceil() it is
      expire_at = Time.now.utc + ttl.ceil
      model.transaction do
        # The DELETE comes first on purpose. On SQLite it takes the database write lock
        # at the very start of the transaction, so the read done by verify_lock_held
        # below is not a read-then-write upgrade - those cannot be resolved by waiting
        # and fail with SQLITE_BUSY_SNAPSHOT instead.
        model.where(idempotent_request_key: key).delete_all

        # With a lease lock our lock can expire while the request is still running - if
        # app.call takes longer than the lease, another request may already have taken
        # over generating this response. We then have no guarantee that our response was
        # generated exclusively, so the only sensible thing to do is to skip the write
        # entirely - including the DELETE, which is why this rolls back.
        raise ActiveRecord::Rollback if verify_lock_held && !verify_lock_held.call

        model.create(idempotent_request_key: key, idempotent_response_payload: data, expire_at: expire_at)
      end
      true
    end
  end

  class PostgresLock
    def acquire(conn, based_on_str)
      acquisition_result = conn.select_value("SELECT pg_try_advisory_lock(%d)" % derive_lock_key(based_on_str))
      [true, "t"].include?(acquisition_result)
    end

    def release(conn, based_on_str)
      conn.select_value("SELECT pg_advisory_unlock(%d)" % derive_lock_key(based_on_str))
    end

    def derive_lock_key(from_str)
      # The key must be a single bigint (signed long)
      hash_bytes = Digest::SHA1.digest(from_str)
      hash_bytes[0...8].unpack1("l_")
    end
  end

  class MysqlLock
    def acquire(connection, based_on_str)
      did_acquire = connection.select_value("SELECT GET_LOCK(%s, %d)" % [connection.quote(derive_lock_name(based_on_str)), 0])
      did_acquire == 1
    end

    def release(connection, based_on_str)
      connection.select_value("SELECT RELEASE_LOCK(%s)" % connection.quote(derive_lock_name(based_on_str)))
    end

    def derive_lock_name(from_str)
      db_safe_key = Base64.strict_encode64(from_str)
      "idempo_%s" % db_safe_key[0...57] # Note there is a limit of 64 bytes on the lock name
    end
  end

  # SQLite has no advisory locks - and barely any write concurrency - but it does give us
  # atomic single-statement upserts, and that is all a lease lock needs. We insert a row
  # carrying a random fencing token into `idempo_locks`; the unique index on the key is
  # what makes the acquisition mutually exclusive. The row carries an expiry so a lock left
  # behind by a crashed process can be taken over later, and the token ensures we only ever
  # release - or write under - a lock we are still holding ourselves.
  #
  # This is the same scheme the RedisBackend uses (SET NX PX + token, delete by token),
  # just expressed as one INSERT ... ON CONFLICT DO UPDATE ... WHERE, which the database
  # applies atomically. Unlike an advisory lock this one is not bound to a connection,
  # which also makes it usable through a transaction-pooling proxy such as PGBouncer.
  class TokenLock
    def initialize(ttl_seconds: LOCK_TTL_SECONDS)
      @ttl_seconds = ttl_seconds
      @token = nil
    end

    def acquire(connection, based_on_str)
      token = SecureRandom.hex(16)
      now = Time.now.utc
      key = derive_lock_key(based_on_str)

      # A single statement, so the database applies it atomically. It inserts when no lock
      # row exists, overwrites the row when the previous lease has expired, and does
      # nothing at all when the lock is currently held by somebody else.
      sql = <<~SQL
        INSERT INTO idempo_locks (idempotent_request_key, lock_token, expire_at)
        VALUES (#{connection.quote(key)}, #{connection.quote(token)}, #{connection.quote(now + @ttl_seconds)})
        ON CONFLICT (idempotent_request_key) DO UPDATE SET
          lock_token = excluded.lock_token,
          expire_at = excluded.expire_at
        WHERE idempo_locks.expire_at <= #{connection.quote(now)}
      SQL
      did_acquire = connection.exec_update(sql, "Idempo lock acquire") == 1
      @token = token if did_acquire
      did_acquire
    end

    def release(connection, based_on_str)
      token = @token or return
      @token = nil
      connection.exec_delete(<<~SQL, "Idempo lock release")
        DELETE FROM idempo_locks
        WHERE idempotent_request_key = #{connection.quote(derive_lock_key(based_on_str))}
          AND lock_token = #{connection.quote(token)}
      SQL
    end

    # Tells whether the lease taken in `acquire` is still ours and has not expired yet
    def held?(connection, based_on_str)
      token = @token or return false
      row = connection.select_value(<<~SQL, "Idempo lock check")
        SELECT 1 FROM idempo_locks
        WHERE idempotent_request_key = #{connection.quote(derive_lock_key(based_on_str))}
          AND lock_token = #{connection.quote(token)}
          AND expire_at > #{connection.quote(Time.now.utc)}
      SQL
      !row.nil?
    end

    def derive_lock_key(from_str)
      Digest::SHA1.base64digest(from_str)
    end
  end

  # Pass `lock:` to override the lock implementation Idempo picks for your database - for
  # example to use the TokenLock on PostgreSQL behind PGBouncer, where advisory locks are
  # not usable. The object needs to respond to `acquire(connection, key)` and
  # `release(connection, key)`, and may respond to `held?(connection, key)`.
  def initialize(lock: nil)
    require "active_record"
    require "securerandom"
    @lock = lock
    @memory_lock = Idempo::MemoryLock.new
  end

  # Allows the model to be defined lazily without having to require active_record when this module gets loaded
  def model
    @model_class ||= Class.new(ActiveRecord::Base) do
      self.table_name = "idempo_responses"
    end
  end

  def lock_model
    @lock_model_class ||= Class.new(ActiveRecord::Base) do
      self.table_name = "idempo_locks"
    end
  end

  def with_idempotency_key(request_key)
    # We need to use an in-memory lock because database advisory locks are
    # reentrant. Both Postgres and MySQL allow multiple acquisitions of the
    # same advisory lock within the same connection - in most Rails/Rack apps
    # this translates to "within the same thread". This means that if one
    # elects to use a non-threading webserver (like Falcon), or tests Idempo
    # within the same thread (like we do), they won't get advisory locking
    # for concurrent requests. Therefore a staged lock is required. First we apply
    # the memory lock (for same thread on this process/multiple threads on this
    # process) and then once we have that - the DB lock.
    @memory_lock.with(request_key) do
      db_safe_key = Digest::SHA1.base64digest(request_key)
      ActiveRecord::Base.connection_pool.with_connection do |connection|
        database_lock = @lock || lock_implementation_for_connection(connection)
        raise Idempo::ConcurrentRequest unless database_lock.acquire(connection, request_key)

        begin
          # Only lease-based locks can be lost while the request is running - an advisory
          # lock is held by the connection for as long as we keep it
          verify_lock_held = -> { database_lock.held?(connection, request_key) } if database_lock.respond_to?(:held?)
          yield(Store.new(db_safe_key, model, verify_lock_held))
        ensure
          database_lock.release(connection, request_key)
        end
      end
    end
  end

  # Deletes expired cached Idempo responses from the database, in batches
  def prune!
    model.where("expire_at < ?", Time.now).in_batches.delete_all
    # Locks for keys which are never requested again would linger otherwise. Guarded
    # because the table may not exist yet on an installation which predates it.
    if lock_model.table_exists?
      lock_model.where("expire_at < ?", Time.now).in_batches.delete_all
    end
  end

  private

  def lock_implementation_for_connection(connection)
    if /^mysql2/i.match?(connection.adapter_name)
      MysqlLock.new
    elsif /^postgres/i.match?(connection.adapter_name)
      PostgresLock.new
    elsif /^sqlite/i.match?(connection.adapter_name)
      TokenLock.new
    else
      raise "Unsupported database driver #{connection.adapter_name.downcase} - we don't know whether it supports advisory locks"
    end
  end
end
